### ISSUE TITLE
Indication on the navbar

### ISSUE THREAD

**Issue by arpit1912** [krish7777/food4all#4]
The navbar currently don't change as per the URL as can be seen below:
![Screenshot from 2020-10-10 14-11-32](https://user-images.githubusercontent.com/46648172/95650680-ab7f0300-0b02-11eb-925d-64535b85ad3f.png)

As one can see the navbar indicate it is a home page but we are on profile page.
How to regenerate this error : type the URL where you want to go in the browser, the page will change but the navbar don't.

**Comment by arpit1912** [comment]
Whoever takes this up please mention it in comments

**Comment by krish7777** [comment]
@arpit1912 I've fixed this issue, will make the changes in  my next PR
