### ISSUE TITLE
Nav bar issue while resizing

### ISSUE THREAD

**Issue by sam3926** [krish7777/food4all#7]
![image](https://user-images.githubusercontent.com/54976429/96337302-c1ad3600-10a3-11eb-80d4-c11a856b66af.png)

On resizing, navbar collapses into two components, the logo div and the menu one. I've been trying to fix it but couldn't. Someone please take this up.

**Comment by sam3926** [comment]
![image](https://user-images.githubusercontent.com/54976429/96338085-55cdcc00-10a9-11eb-9a63-27df858f886f.png)


Onother issue, some nav bar options become collapsible even while in full screen

**Comment by krish7777** [comment]
@sam3926 I've resolved this issue ; will push in the next PR.

**Comment by sam3926** [comment]
> @sam3926 I've resolved this issue ; will push in the next PR.

Cool, I'd fixed the first issue, do check it out
